backend/src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    #[Groups(['car_list', 'car_favorite_list'])]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Groups('car_list',)]
    private ?string $brand = null;

    #[ORM\Column(length: 100)]
    #[Groups('car_list')]
    private ?string $model = null;

    #[ORM\Column]
    #[Groups('car_list')]
    private ?int $manufacture_year = null;

    #[ORM\Column]
    #[Groups('car_list')]
    private ?int $mileage = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Groups('car_list')]
    private ?string $price = null;

    #[ORM\Column(length: 50)]
    #[Groups('car_list')]
    private ?string $color = null;

    #[ORM\Column(length: 50)]
    #[Groups('car_list')]
    private ?string $fuelType = null;

    #[ORM\Column(length: 50)]
    #[Groups('car_list')]
    private ?string $transmission = null;

    #[ORM\Column(length: 50)]
    #[Groups('car_list')]
    private ?string $traction = null;

    #[ORM\Column]
    #[Groups('car_list')]
    private ?int $doors = null;

    #[ORM\Column]
    #[Groups('car_list')]
    private ?int $seats = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Groups('car_list')]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups('car_list')]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column(length: 50)]
    #[Groups('car_list')]
    private ?string $CarCondition = null;

    #[ORM\Column(type: "json", nullable: true)]
    #[Groups('car_list')]
    private ?array $images = null;

    #[ORM\Column(name: "car_status", type: Types::STRING, length: 50)]
    #[Groups('car_list')]
    private ?string $CarSold = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[Groups('car_list')]
    private ?User $user = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 6)]
    #[Groups('car_list')]
    private ?string $lat = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 6)]
    #[Groups('car_list')]
    private ?string $lon = null;

    #[ORM\Column(length: 255)]
    #[Groups('car_list')]
    private ?string $city = null;

    

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;
        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;
        return $this;
    }

    public function getManufactureYear(): ?int
    {
        return $this->manufacture_year;
    }

    public function setManufactureYear(int $manufacture_year): static
    {
        $this->manufacture_year = $manufacture_year;
        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(int $mileage): static
    {
        $this->mileage = $mileage;
        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;
        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;
        return $this;
    }

    public function getFuelType(): ?string
    {
        return $this->fuelType;
    }

    public function setFuelType(string $fuelType): static
    {
        $this->fuelType = $fuelType;
        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): static
    {
        $this->transmission = $transmission;
        return $this;
    }

    public function getTraction(): ?string
    {
        return $this->traction;
    }

    public function setTraction(string $traction): static
    {
        $this->traction = $traction;
        return $this;
    }

    public function getDoors(): ?int
    {
        return $this->doors;
    }

    public function setDoors(int $doors): static
    {
        $this->doors = $doors;
        return $this;
    }

    public function getSeats(): ?int
    {
        return $this->seats;
    }

    public function setSeats(int $seats): static
    {
        $this->seats = $seats;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;
        return $this;
    }

    public function getCarCondition(): ?string
    {
        return $this->CarCondition;
    }

    public function setCarCondition(string $CarCondition): static
    {
        $this->CarCondition = $CarCondition;
        return $this;
    }

    public function getImages(): ?array
    {
        return $this->images;
    }

    public function setImages(?array $images): static
    {
        $this->images = $images;
        return $this;
    }

    public function getCarSold(): ?string
    {
        return $this->CarSold;
    }

    public function setCarSold(string $CarSold): static
    {
        $this->CarSold = $CarSold;
        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $User): static
    {
        $this->user = $User;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(string $lat): static
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLon(): ?string
    {
        return $this->lon;
    }

    public function setLon(string $lon): static
    {
        $this->lon = $lon;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }
}

backend/src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('brand')
            ->add('model')
            ->add('manufacture_year')
            ->add('mileage')
            ->add('price')
            ->add('color')
            ->add('fuelType')
            ->add('transmission')
            ->add('traction')
            ->add('doors')
            ->add('seats')
            ->add('description')
            ->add('publication_date')
            ->add('CarCondition')
            ->add('CarSold')
            ->add('lat')
            ->add('lon')
            ->add('city');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

backend/src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\User;
use App\Repository\CarRepository;
use App\Service\CloudinaryService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;


#[Route('/car')]
class CarController extends AbstractController
{
    #[Route('/', name: 'app_car_index', methods: ['GET'])]
    public function index(CarRepository $carRepository, SerializerInterface $serializer, Request $request): Response
    {
        $page = (int) $request->query->get('page', 1);
        $limit = (int) $request->query->get('limit', 10);
        $offset = ($page - 1) * $limit;

        // Obtener coches y el total de coches
        $cars = $carRepository->findMostFavoriteCars($limit, $offset);
        $totalCars = count($carRepository->findMostFavoriteCars(100, 0)); // Obtener el total de coches (sin paginación)

        if (empty($cars)) {
            return new JsonResponse(['message' => 'No cars found'], Response::HTTP_NOT_FOUND);
        }

        $jsonCars = $serializer->serialize($cars, 'json', ['groups' => 'car_list']);

        // Calcular el total de páginas
        $totalPages = ceil($totalCars / $limit);

        return new JsonResponse([
            'cars' => json_decode($jsonCars),
            'totalCars' => $totalCars,
            'totalPages' => $totalPages,
            'currentPage' => $page
        ], Response::HTTP_OK);
    }


    #[Route('/user/{id}', name: 'app_car_index_by_user', methods: ['GET'])]
    public function indexByUser(CarRepository $carRepository, SerializerInterface $serializer, $id): Response
    {
        $cars = $carRepository->findBy(['user' => $id]);

        if (empty($cars)) {
            return new JsonResponse(['message' => 'No cars found for this user'], Response::HTTP_NOT_FOUND);
        }

        $jsonCars = $serializer->serialize($cars, 'json', ['groups' => 'car_list']);
        return new JsonResponse($jsonCars, Response::HTTP_OK, [], true);
    }

    #[Route('/new', name: 'app_car_new', methods: ['POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, CloudinaryService $cloudinaryService): Response
    {
        $car = new Car();
        $formData = $request->request->all();
        $images = $request->files->get('images');

        $imageUrls = [];
        if ($images) {
            foreach ($images as $image) {
                if ($image && $image->isValid()) {
                    try {
                        $url = $cloudinaryService->uploadImage($image->getPathname());
                        $imageUrls[] = $url;
                    } catch (\Exception $e) {
                        return $this->json([
                            'status' => 'error',
                            'message' => 'Error al subir la imagen: ' . $e->getMessage()
                        ], Response::HTTP_BAD_REQUEST);
                    }
                }
            }
        }

        $car->setPublicationDate(new \DateTime());

        $car->setBrand($formData['brand']);
        $car->setModel($formData['model']);
        $car->setManufactureYear($formData['manufacture_year']);
        $car->setMileage($formData['mileage']);
        $car->setPrice($formData['price']);
        $car->setColor($formData['color']);
        $car->setFuelType($formData['fuelType']);
        $car->setTransmission($formData['transmission']);
        $car->setTraction($formData['traction']);
        $car->setDoors($formData['doors']);
        $car->setSeats($formData['seats']);
        $car->setDescription($formData['description']);
        $car->setCarCondition($formData['carCondition']);
        $car->setCarSold('subido');
        $car->setLat($formData['lat']);
        $car->setLon($formData['lon']);
        $car->setCity($formData['city']);
        $car->setImages($imageUrls);

        $user = $entityManager->getRepository(User::class)->find($formData['user']);
        if (!$user) {
            return $this->json(['status' => 'error', 'message' => 'Usuario no encontrado.'], Response::HTTP_BAD_REQUEST);
        }

        $car->setUser($user);
        $entityManager->persist($car);
        $entityManager->flush();

        return $this->json(['status' => 'ok', 'message' => 'Coche creado con éxito']);
    }

    #[Route('/{id}', name: 'app_car_show', methods: ['GET'])]
    public function showById(CarRepository $carRepository, SerializerInterface $serializer, $id): Response
    {
        $car = $carRepository->find($id);

        if (!$car) {
            return new JsonResponse(['message' => 'No car found'], Response::HTTP_NOT_FOUND);
        }

        $jsonCar = $serializer->serialize($car, 'json', ['groups' => 'car_list']);
        return new JsonResponse(json_decode($jsonCar), Response::HTTP_OK);
    }

    #[Route('/{id}/edit', name: 'app_car_edit', methods: ['PATCH'])]
    public function edit(Request $request, Car $car, EntityManagerInterface $entityManager): Response
    {
        $data = json_decode($request->getContent(), true);

        if (isset($data['brand'])) $car->setBrand($data['brand']);
        if (isset($data['model'])) $car->setModel($data['model']);
        if (isset($data['manufacture_year'])) $car->setManufactureYear($data['manufacture_year']);
        if (isset($data['mileage'])) $car->setMileage($data['mileage']);
        if (isset($data['price'])) $car->setPrice($data['price']);
        if (isset($data['color'])) $car->setColor($data['color']);
        if (isset($data['fuelType'])) $car->setFuelType($data['fuelType']);
        if (isset($data['transmission'])) $car->setTransmission($data['transmission']);
        if (isset($data['traction'])) $car->setTraction($data['traction']);
        if (isset($data['doors'])) $car->setDoors($data['doors']);
        if (isset($data['seats'])) $car->setSeats($data['seats']);
        if (isset($data['description'])) $car->setDescription($data['description']);
        if (isset($data['carCondition'])) $car->setCarCondition($data['carCondition']);
        if (isset($data['images'])) $car->setImages($data['images']);
        if (isset($data['carSold'])) $car->setCarSold($data['carSold']);
        if (isset($data['lat'])) $car->setLat($data['lat']);
        if (isset($data['lon'])) $car->setLon($data['lon']);
        if (isset($data['city'])) $car->setCity($data['city']);

        try {
            $entityManager->flush();
            return new JsonResponse(['status' => 'success', 'message' => 'Car updated successfully'], Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse([
                'status' => 'error',
                'message' => 'Failed to update car details',
                'error' => $e->getMessage()
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/{id}/delete', name: 'app_car_delete', methods: ['DELETE'])]
    public function delete(Request $request, Car $car, EntityManagerInterface $entityManager): Response
    {
        try {
            $entityManager->remove($car);
            $entityManager->flush();

            return new JsonResponse([
                'status' => 'correcto',
                'message' => 'Coche eliminado correctamente'
            ], Response::HTTP_OK);
        } catch (\Exception $e) {
            return new JsonResponse([
                'status' => 'no',
                'message' => 'Error al eliminar el coche',
                'error' => $e->getMessage()
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}

backend/templates/car/_delete_form.html.twig
<form method="post" action="{{ path('app_car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn">Delete</button>
</form>

backend/templates/car/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_row(form.images) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

backend/templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Car{% endblock %}

{% block body %}
    <h1>Edit Car</h1>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_car_index') }}">back to list</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}

backend/templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car index{% endblock %}

{% block body %}
    <h1>Car index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Manufacture_year</th>
                <th>Mileage</th>
                <th>Price</th>
                <th>Color</th>
                <th>FuelType</th>
                <th>Transmission</th>
                <th>Traction</th>
                <th>Doors</th>
                <th>Seats</th>
                <th>Description</th>
                <th>Publication_date</th>
                <th>CarCondition</th>
                <th>Images</th>
                <th>CarSold</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{ car.id }}</td>
                <td>{{ car.brand }}</td>
                <td>{{ car.model }}</td>
                <td>{{ car.manufactureYear }}</td>
                <td>{{ car.mileage }}</td>
                <td>{{ car.price }}</td>
                <td>{{ car.color }}</td>
                <td>{{ car.fuelType }}</td>
                <td>{{ car.transmission }}</td>
                <td>{{ car.traction }}</td>
                <td>{{ car.doors }}</td>
                <td>{{ car.seats }}</td>
                <td>{{ car.description }}</td>
                <td>{{ car.publicationDate ? car.publicationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ car.CarCondition }}</td>
                <td>{{ car.images ? car.images|json_encode : '' }}</td>
                <td>{{ car.CarSold ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_car_show', {'id': car.id}) }}">show</a>
                    <a href="{{ path('app_car_edit', {'id': car.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="18">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_car_new') }}">Create new</a>
{% endblock %}

backend/templates/car/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Car{% endblock %}

{% block body %}
    <h1>Create new Car</h1>
    {{ form_start(form, {'enctype': 'multipart/form-data'}) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('app_car_index') }}">back to list</a>
{% endblock %}

backend/templates/car/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car{% endblock %}

{% block body %}
    <h1>Car</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ car.id }}</td>
            </tr>
            <tr>
                <th>Brand</th>
                <td>{{ car.brand }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ car.model }}</td>
            </tr>
            <tr>
                <th>Manufacture_year</th>
                <td>{{ car.manufactureYear }}</td>
            </tr>
            <tr>
                <th>Mileage</th>
                <td>{{ car.mileage }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ car.price }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ car.color }}</td>
            </tr>
            <tr>
                <th>FuelType</th>
                <td>{{ car.fuelType }}</td>
            </tr>
            <tr>
                <th>Transmission</th>
                <td>{{ car.transmission }}</td>
            </tr>
            <tr>
                <th>Traction</th>
                <td>{{ car.traction }}</td>
            </tr>
            <tr>
                <th>Doors</th>
                <td>{{ car.doors }}</td>
            </tr>
            <tr>
                <th>Seats</th>
                <td>{{ car.seats }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ car.description }}</td>
            </tr>
            <tr>
                <th>Publication_date</th>
                <td>{{ car.publicationDate ? car.publicationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>CarCondition</th>
                <td>{{ car.CarCondition }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>{{ car.images ? car.images|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>CarSold</th>
                <td>{{ car.CarSold ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_car_index') }}">back to list</a>

    <a href="{{ path('app_car_edit', {'id': car.id}) }}">edit</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}